<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

function formatDecimal($value)
{
    $value = str_replace(',', '.', $value);

    if (!is_numeric($value)) {
        throw new \InvalidArgumentException('Value must be a valid number.');
    }

    return $value;
}

/**
 * Generate a session ID based on the user's User-Agent, IP address, and phone number.
 *
 * @param Request $request
 *
 * @return string
 */
function getSessionId(Request $request): string
{
    $userAgent = $request->header('User-Agent') ?? 'unknown';
    $ipAddress = $request->ip() ?? '0.0.0.0';

    $phone = Auth::user()->phone ?? 'unknown';

    $sessionId = hash('sha256', $userAgent . '|' . $ipAddress . '|' . $phone);

    return $sessionId;
}

/**
 * Verify session ID sent from frontend matches with the one generated by this application based on user's User-Agent and IP address.
 *
 * @param Request $request
 *
 * @return bool
 */
function verifySessionId(Request $request, string $sessionId): bool
{
    // Buat ulang session ID berdasarkan data sekarang
    $generatedSessionId = getSessionId($request);

    // Bandingkan apakah session ID yang dikirim cocok dengan yang kita generate
    if ($generatedSessionId === $sessionId) {
        return true;
    }

    return false;
}
